# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
#image: registry.gitlab.com/pages/hugo/hugo_extended:latest

#variables:
#  GIT_SUBMODULE_STRATEGY: recursive

#pages:
#  script:
#  - echo The script part is required in 'pages' section
  # - hugo
#  artifacts:
#    paths:
#    - public
#  only:
#  - master

#before_script:
#  - apk add --update --no-cache git

image: node:latest

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm ci
  - npm test
  - npm run build

  artifacts:
    paths:
    - public
  only:
    - master
